services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    networks:
      - imc-network
networks:
  imc-network:
    external: true
    name: imc-network
